### ISSUE TITLE
Data ValueError: time data '2020-02-24T18:00:00' does not match format '%Y-%m-%d %H:%M:%S'

### ISSUE THREAD

**Issue by massimobosetti** [glpatcern/inotebooks#1]
ValueError                                Traceback (most recent call last)
<ipython-input-5-cedcab81e4f1> in <module>
     10 
     11   # convert date format to days since Feb 29th
---> 12   regdf[r]['date'] = regdf[r]['date'].map(lambda d : \
     13         (datetime.strptime(d, '%Y-%m-%d %H:%M:%S') - datetime.strptime('2020-02-29','%Y-%m-%d')).days)
     14 

~/anaconda3/lib/python3.7/site-packages/pandas/core/series.py in map(self, arg, na_action)
   3628         dtype: object
   3629         """
-> 3630         new_values = super()._map_values(arg, na_action=na_action)
   3631         return self._constructor(new_values, index=self.index).__finalize__(self)
   3632 

~/anaconda3/lib/python3.7/site-packages/pandas/core/base.py in _map_values(self, mapper, na_action)
   1143 
   1144         # mapper is a function
-> 1145         new_values = map_f(values, mapper)
   1146 
   1147         return new_values

pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

<ipython-input-5-cedcab81e4f1> in <lambda>(d)
     11   # convert date format to days since Feb 29th
     12   regdf[r]['date'] = regdf[r]['date'].map(lambda d : \
---> 13         (datetime.strptime(d, '%Y-%m-%d %H:%M:%S') - datetime.strptime('2020-02-29','%Y-%m-%d')).days)
     14 
     15   # convert #cases to cases per 1M inhabitants

~/anaconda3/lib/python3.7/_strptime.py in _strptime_datetime(cls, data_string, format)
    575     """Return a class cls instance based on the input string and the
    576     format string."""
--> 577     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    578     tzname, gmtoff = tt[-2:]
    579     args = tt[:6] + (fraction,)

~/anaconda3/lib/python3.7/_strptime.py in _strptime(data_string, format)
    357     if not found:
    358         raise ValueError("time data %r does not match format %r" %
--> 359                          (data_string, format))
    360     if len(data_string) != found.end():
    361         raise ValueError("unconverted data remains: %s" %

ValueError: time data '2020-02-24T18:00:00' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by glpatcern** [comment]
Salve,

Notando che in generale e' consigliabile scrivere qualche commento in un issue, ed eventualmente copiare l'errore in formato "codice":

```
358 raise ValueError("time data %r does not match format %r" %
--> 359 (data_string, format))
360 if len(data_string) != found.end():
361 raise ValueError("unconverted data remains: %s" %

ValueError: time data '2020-02-24T18:00:00' does not match format '%Y-%m-%d %H:%M:%S'
```

In questo caso il problema come dall'esempio e' dovuto al fatto che la Protezione Civile ha cambiato il formato dei dati inserendo la `T` tra data e ora. Basta correggere la stringa di formato in modo che diventi `%Y-%m-%dT%H:%M:%S`. Modifichero' il codice su Github appena posso.

**Comment by massimobosetti** [comment]
Buongiorno Giuseppe,
grazie per le informazioni, al prossimo issue ne terrò conto.lo avevo immaginato ma non riuscivo a capire come modificarlo.
Ora modifico il mio.
un saluto dal Trentino.
m

**Comment by glpatcern** [comment]
Perfetto, nel frattempo ho aggiornato il codice qui su Github.
Saluti a te da Ginevra.
